### ISSUE TITLE
ImportError: cannot import name 'db_connect'

### ISSUE THREAD

**Issue by pierretamisier** [ethanopp/fitly#10]
I think [6ca2f5463889c6ad09fda41c46d437863acfea9b](https://github.com/ethanopp/fitly/commit/6ca2f5463889c6ad09fda41c46d437863acfea9b#diff-716f05cd9665af080b88ea0355f2992e) leads to the below issue.

```
(env) pierre@pierre-thinkpad:~/Workspace/fitly(master)$ run-fitly-dev 
Traceback (most recent call last):
  File "/home/pierre/Workspace/fitly/env/bin/run-fitly-dev", line 11, in <module>
    load_entry_point('Fit.ly', 'console_scripts', 'run-fitly-dev')()
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pierre/Workspace/fitly/src/fitly/dev_cli.py", line 5, in <module>
    from .app import app
  File "/home/pierre/Workspace/fitly/src/fitly/app.py", line 32, in <module>
    from . import index
  File "/home/pierre/Workspace/fitly/src/fitly/index.py", line 5, in <module>
    from .pages import home, lifting, performance, power, settings
  File "/home/pierre/Workspace/fitly/src/fitly/pages/settings.py", line 8, in <module>
    from ..api.ouraAPI import oura_connected, connect_oura_link, save_oura_token
  File "/home/pierre/Workspace/fitly/src/fitly/api/ouraAPI.py", line 2, in <module>
    from ..api.sqlalchemy_declarative import db_connect, db_insert, ouraReadinessSummary, ouraActivitySummary, \
ImportError: cannot import name 'db_connect'
```

**Comment by ethanopp** [comment]
Yeah I made some significant changes to handle the threading issues... Repull the entire repo from scratch and pip install -e <path>

**Comment by pierretamisier** [comment]
indeed - cheers!
