### ISSUE TITLE
Trouble connecting oura

### ISSUE THREAD

**Issue by spawn-github** [ethanopp/fitly#14]
Hi, was having trouble trying to connect my oura account. I hit the 'connect oura' button on the setting page, I was redirected to the oura page to grant access to the app, I accept the grant, andwas redirected back the settings page, with the 'connect oura' button still there.  In the debug output I see:

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1076, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1007, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/app/src/fitly/pages/settings.py", line 1093, in update_tokens
    oura_auth_client.fetch_access_token(parse_qs(query_params.query)['code'][0])
KeyError: 'code'

Turns out the callback url to fitly contained an additional "?" (after /settings?oura) and converting the second "?" to an "&" then re-submitting the callback url connected  the oura account.

Not sure if there's anything you can do about it, but might help someone else if they see this.

**Comment by ethanopp** [comment]
Should be good now with above https://github.com/ethanopp/fitly/commit/934a5a45561e18928c69f24bcb2d04d4394991f8

**Comment by spawn-github** [comment]
FYI, since I needed to reconnect oura for #15, I ran into the same issue (extra ? in the url), so don't think the above fix was effective.

**Comment by ethanopp** [comment]
The ? will still show in the URL (can't change that as that is how oura sends the code back). The fix should be parsing that URL with the additional ? correctly now though. As long as after you connect you get the 'Oura Connected' you should be good

**Comment by spawn-github** [comment]
I must not have been on the fixed image at the time, as with the latest image I was able to connect to oura without issue/workarounds. 

So confirmed the fix is good. Thanks!
