### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nncrypted** [ethanopp/fitly#18]
Tried to run the docker container from Windows and from Linux both get this error. Any insight?

Checking for script in /app/prestart.sh

Running script /app/prestart.sh

Running inside /app/prestart.sh, you could add migrations to this file, e.g.:

#! /usr/bin/env bash

# Let the DB start



sleep 10;

# Run migrations

alembic upgrade head

{"loglevel": "info", "workers": 16, "bind": "0.0.0.0:80", "workers_per_core": 2.0, "host": "0.0.0.0", "port": "80"}

Traceback (most recent call last):

File "/usr/local/bin/gunicorn", line 8, in <module>

sys.exit(run())

File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in run

WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()

File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 228, in run

super().run()

File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run

Arbiter(self).run()

File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 58, in __init__

self.setup(app)

File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 118, in setup

self.app.wsgi()

File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi

self.callable = self.load()

File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load

return self.load_wsgiapp()

File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp

return util.import_app(self.app_uri)

File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app

mod = importlib.import_module(module)

File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

File "<frozen importlib._bootstrap>", line 983, in _find_and_load

File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

File "<frozen importlib._bootstrap>", line 983, in _find_and_load

File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 677, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 728, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "/app/src/fitly/__init__.py", line 5, in <module>

from .utils import get_dash_args_from_flask_config

File "/app/src/fitly/utils.py", line 167, in <module>

local_tz = pytz.timezone(config.get('timezone', 'timezone'))

File "/usr/local/lib/python3.7/configparser.py", line 780, in get

d = self._unify_values(section, vars)

File "/usr/local/lib/python3.7/configparser.py", line 1146, in _unify_values

raise NoSectionError(section) from None

configparser.NoSectionError: No section: 'timezone'

**Comment by ethanopp** [comment]
It looks like you may not have a timezone specified in your config.ini
https://github.com/ethanopp/fitly/blob/a556a5be998618288c199d05aaa1a8ef499d8473/config/config.ini.example#L63

**Comment by nncrypted** [comment]
I've tried every variation it doesn't create anything in the directory so I cloned your repo into the directory still get the same error. Am I doing something wrong or have I missed a step?

**Comment by nncrypted** [comment]
Under windows docker I'm using this command and getting the above error:

docker create --name=fitly --restart unless-stopped -e MODULE_NAME=src.fitly.app -e VARIABLE_NAME=server -e TZ=America/New_York -e TIMEOUT=1200 -e DASH_DEBUG=true -p 8050:80 -v D:\fitly:\app\config ethanopp/fitly:latest

**Comment by ethanopp** [comment]
Did you set up your config.ini?

**Comment by nncrypted** [comment]
Nothing to set up as it never actually boots or creates any files just keeps restarting with that error.

**Comment by ethanopp** [comment]
https://github.com/ethanopp/fitly#configuring-your-app

**Comment by nncrypted** [comment]
Ok awesome. My directory structure was wrong I guess it's up and running thank you super cool project

**Comment by ethanopp** [comment]
Great glad you got it up!
