### ISSUE TITLE
errors running in docker

### ISSUE THREAD

**Issue by nncrypted** [ethanopp/fitly#19]
Exception on /_dash-update-component [POST]

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app

    response = self.full_dispatch_request()

  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception

    reraise(exc_type, exc_value, tb)

  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise

    raise value

  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request

    rv = self.dispatch_request()

  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1078, in dispatch

    response.set_data(func(*args, outputs_list=outputs_list))

  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1009, in add_context

    output_value = func(*args, **kwargs)  # %% callback invoked %%

  File "/app/src/fitly/pages/power.py", line 1110, in update_power_curve

    figure = power_curve(activity_type, power_unit)

  File "/app/src/fitly/pages/power.py", line 416, in power_curve

    interval_lengths += [i for i in range(1230, (int(math.floor(max_interval / 10.0)) * 10) + 1, 30)]

TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

**Comment by nncrypted** [comment]
also getting the following:
Unsupported <enum 'MeasureType'> value 123. Replacing with UNKNOWN value MeasureType.UNKNOWN. Please report this warning to the developer to ensure proper support.

**Comment by ethanopp** [comment]
Can you check your database and see if you have any data in the strava_best_samples table?

**Comment by nncrypted** [comment]
It's empty

**Comment by ethanopp** [comment]
Ah that would mean you did not pull any data then yet. Turn on debug mode in the log section and click the refresh button 
![image](https://user-images.githubusercontent.com/11603814/110518155-c5386c80-80d9-11eb-93f0-03645839c836.png)

**Comment by nncrypted** [comment]
Still doesn't work. Lots of errors like above also I can't add myself as an athlete.

**Comment by ethanopp** [comment]
What does the log say

**Comment by nncrypted** [comment]
[2021-03-09 13:52:18,731] ERROR from app line 1892 - Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/app/src/fitly/pages/performance.py", line 3441, in update_yoy_chart
    figure, hoverData = create_yoy_chart(sport=sport, metric=metric)
  File "/app/src/fitly/pages/performance.py", line 1836, in create_yoy_chart
    df['year'] = df.index.year
AttributeError: 'Index' object has no attribute 'year'
[2021-03-09 13:52:18,769] ERROR from app line 1892 - Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/app/src/fitly/pages/performance.py", line 3262, in refresh_fitness_chart
    atl_status=atl_status)
  File "/app/src/fitly/pages/performance.py", line 2054, in create_fitness_chart
    df_summary.loc[df_summary['new_run_ftp_flag'] == 1, 'tss_flag'] = 1
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 692, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1588, in _setitem_with_indexer
    "cannot set a frame with no "
ValueError: cannot set a frame with no defined index and a scalar
[2021-03-09 13:52:18,790] ERROR from app line 1892 - Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/app/src/fitly/pages/performance.py", line 3348, in update_trend_chart
    figure = get_trend_chart(metric=metric, sport=sport, days=days, intensity=last_intensity_click)
  File "/app/src/fitly/pages/performance.py", line 1038, in get_trend_chart
    df = df[df['start_date_local_x'].dt.date >= date]
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 5461, in __getattr__
    return object.__getattribute__(self, name)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/accessor.py", line 180, in __get__
    accessor_obj = self._accessor(obj)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/accessors.py", line 494, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values
[2021-03-09 13:52:18,854] ERROR from app line 1892 - Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/app/src/fitly/pages/performance.py", line 3406, in update_icon
    activity_type=sport, height=200, time_comparison=days, intensity=last_intensity_click) if use_power else {}, {
  File "/app/src/fitly/pages/power.py", line 416, in power_curve
    interval_lengths += [i for i in range(1230, (int(math.floor(max_interval / 10.0)) * 10) + 1, 30)]
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
[2021-03-09 13:55:18,566] INFO from settings line 933 - Updating auto-generate spotify playlists = True
[2021-03-09 13:55:18,570] INFO from settings line 950 - Updating spotify_use_rec_intensity = True
[2021-03-09 13:55:18,576] DEBUG from settings line 1001 - use-run-power set to False, use-cycle-power set to True
[2021-03-09 13:55:18,663] INFO from settings line 1204 - Log level set to DEBUG
[2021-03-09 13:55:18,900] DEBUG from stravaApi line 67 - Strava connected
[2021-03-09 13:55:19,499] ERROR from api_withings line 51 - Withings not connected
[2021-03-09 13:55:19,500] ERROR from api_withings line 52 - Error code 401
[2021-03-09 13:55:19,506] ERROR from spotifyAPI line 55 - 'NoneType' object has no attribute 'tokens'
[2021-03-09 13:55:19,659] ERROR from spotifyAPI line 85 - Spotify not connected
[2021-03-09 13:55:19,660] ERROR from spotifyAPI line 86 - Error in https://api.spotify.com/v1/me/top/tracks?time_range=medium_term&limit=10&offset=0:
401: Invalid access token

**Comment by ethanopp** [comment]
Have you connected all the accounts you are trying to use? 
![image](https://user-images.githubusercontent.com/11603814/110523207-ca001f00-80df-11eb-88ed-173cd55ca72c.png)

**Comment by nncrypted** [comment]
Yes, Withthings had disconnected but it's reconnected now.

**Comment by ethanopp** [comment]
Clear the log and then 'refresh' and paste here

**Comment by nncrypted** [comment]
[2021-03-09 14:06:52,071] ERROR from app line 1892 - Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/app/src/fitly/pages/performance.py", line 3441, in update_yoy_chart
    figure, hoverData = create_yoy_chart(sport=sport, metric=metric)
  File "/app/src/fitly/pages/performance.py", line 1836, in create_yoy_chart
    df['year'] = df.index.year
AttributeError: 'Index' object has no attribute 'year'
[2021-03-09 14:06:52,107] ERROR from app line 1892 - Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/app/src/fitly/pages/performance.py", line 3262, in refresh_fitness_chart
    atl_status=atl_status)
  File "/app/src/fitly/pages/performance.py", line 2054, in create_fitness_chart
    df_summary.loc[df_summary['new_run_ftp_flag'] == 1, 'tss_flag'] = 1
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 692, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1588, in _setitem_with_indexer
    "cannot set a frame with no "
ValueError: cannot set a frame with no defined index and a scalar
[2021-03-09 14:06:52,108] ERROR from app line 1892 - Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/app/src/fitly/pages/performance.py", line 3348, in update_trend_chart
    figure = get_trend_chart(metric=metric, sport=sport, days=days, intensity=last_intensity_click)
  File "/app/src/fitly/pages/performance.py", line 1038, in get_trend_chart
    df = df[df['start_date_local_x'].dt.date >= date]
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 5461, in __getattr__
    return object.__getattribute__(self, name)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/accessor.py", line 180, in __get__
    accessor_obj = self._accessor(obj)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/accessors.py", line 494, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values
[2021-03-09 14:06:52,225] ERROR from app line 1892 - Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/app/src/fitly/pages/performance.py", line 3406, in update_icon
    activity_type=sport, height=200, time_comparison=days, intensity=last_intensity_click) if use_power else {}, {
  File "/app/src/fitly/pages/power.py", line 416, in power_curve
    interval_lengths += [i for i in range(1230, (int(math.floor(max_interval / 10.0)) * 10) + 1, 30)]
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
[2021-03-09 14:06:55,066] ERROR from app line 1892 - Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/app/src/fitly/pages/power.py", line 1110, in update_power_curve
    figure = power_curve(activity_type, power_unit)
  File "/app/src/fitly/pages/power.py", line 416, in power_curve
    interval_lengths += [i for i in range(1230, (int(math.floor(max_interval / 10.0)) * 10) + 1, 30)]
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
[2021-03-09 14:06:56,512] ERROR from app line 1892 - Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/app/src/fitly/pages/power.py", line 1110, in update_power_curve
    figure = power_curve(activity_type, power_unit)
  File "/app/src/fitly/pages/power.py", line 416, in power_curve
    interval_lengths += [i for i in range(1230, (int(math.floor(max_interval / 10.0)) * 10) + 1, 30)]
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
[2021-03-09 14:06:59,600] DEBUG from settings line 1001 - use-run-power set to False, use-cycle-power set to True
[2021-03-09 14:06:59,604] INFO from settings line 933 - Updating auto-generate spotify playlists = False
[2021-03-09 14:06:59,612] INFO from settings line 1204 - Log level set to DEBUG
[2021-03-09 14:06:59,613] INFO from settings line 950 - Updating spotify_use_rec_intensity = True
[2021-03-09 14:07:00,027] DEBUG from stravaApi line 67 - Strava connected
[2021-03-09 14:07:00,572] DEBUG from api_withings line 48 - Withings Connected
[2021-03-09 14:07:00,577] ERROR from spotifyAPI line 55 - 'NoneType' object has no attribute 'tokens'
[2021-03-09 14:07:00,734] ERROR from spotifyAPI line 85 - Spotify not connected
[2021-03-09 14:07:00,735] ERROR from spotifyAPI line 86 - Error in https://api.spotify.com/v1/me/top/tracks?time_range=medium_term&limit=10&offset=0:
401: Invalid access token

**Comment by ethanopp** [comment]
Delete your .db file and start over from instructions in readme - none of the pages are going to work until you download strava data so going to them sill just give you all of those random errors

**Comment by nncrypted** [comment]
That didn't work however what seems to have worked was manually editing the db file with my athlete details and now its pulling the data. I also had to chmod 777 the db file. Thanx for your patience and help getting this going.

**Comment by ethanopp** [comment]
Great glad you got it!
