### ISSUE TITLE
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread

### ISSUE THREAD

**Issue by pierretamisier** [ethanopp/fitly#6]
I use fitly with Oura & Strava credentials only.
When I do Settings > Truncate All I see what seems to be multithreading issues during the Strava import?

```
New Workout found: London
Exception during reset or similar
Traceback (most recent call last):
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/werkzeug/local.py", line 72, in __getattr__
    return self.__storage__[self.__ident_func__()][name]
KeyError: 139767122663168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 543, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139767150724864 and this is thread id 139767122663168.
Exception closing connection <sqlite3.Connection object at 0x7f1e10b7dc70>
Traceback (most recent call last):
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/werkzeug/local.py", line 72, in __getattr__
    return self.__storage__[self.__ident_func__()][name]
KeyError: 139767122663168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 543, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139767150724864 and this is thread id 139767122663168.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 270, in _close_connection
    self._dialect.do_close(connection)
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 549, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139767150724864 and this is thread id 139767122663168.
Inserting records into db_refresh...
Refresh Complete
```

It doesn't happen every time though.

**Comment by ethanopp** [comment]
In your config.ini do you have the hourly cron setting as true? If so it may be trying to run the job in parallel if you have a job running (manually) that crosses past the hour. 

For the initial load ( or when doing a full db reset ) try setting that hourly setting to False.

Let me know if that does is and if so I can write some code that will prevent the cron from triggering if there is another refresh in progress

**Comment by pierretamisier** [comment]
I havent changed the hourly_pull for the corn, it is set to:
```
[cron]
hourly_pull = False
```

Maybe it has to do with background processes linked to run-fitly-dev that I haven't exited properly? Sometimes the app crashes when I save the code with incorrect syntax, etc.

**Comment by ethanopp** [comment]
Yeah you definitely need to make sure you fully stop the server that's running... Also check that your aren't hitting you strava api limit

**Comment by ethanopp** [comment]
I did notice there were several areas where I had some sessions that could potentially have been being left open - check https://github.com/ethanopp/fitly/commit/b61f8e08582305b5e20d715360e123e69ac3aa1f

**Comment by pierretamisier** [comment]
Seems to have helped! Thanks!

**Comment by pierretamisier** [comment]
Actually I managed to reproduce the issue when doing 'Truncate All'. I copy the debug info for future reference.

```
...
Pulling activity from max date in oura_activity_summary 1999-01-01
Pulling sleep from max date in oura_sleep_summary 1999-01-01
Deleting >= 1999-01-01 records from oura_readiness_summary
Inserting oura readiness summary
Deleting >= 1999-01-01 records from oura_activity_summary
Deleting >= 1999-01-01 records from oura_activity_samples
Inserting oura activity summary
Inserting oura activity samples
Deleting >= 1999-01-01 records from oura_sleep_summary
Deleting >= 1999-01-01 records from oura_sleep_samples
Inserting oura sleep summary
Exception during reset or similar
Traceback (most recent call last):
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 543, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139998794790656 and this is thread id 139998810523392.
Exception closing connection <sqlite3.Connection object at 0x7f53e748a9d0>
Traceback (most recent call last):
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 543, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139998794790656 and this is thread id 139998810523392.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 270, in _close_connection
    self._dialect.do_close(connection)
  File "/home/pierre/Workspace/fitly/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 549, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139998794790656 and this is thread id 139998810523392.
Pulling strava data...
Strava connected
New Workout found: "A Dance With The Bull - Tuiaponie-ata"
New Workout found: "Morning Swim"
New Workout found: "Afternoon Run"
New Workout found: "Morning Swim"
New Workout found: "Lunch Activity"
New Workout found: "Morning Run"
New Workout found: "Morning Swim"
New Workout found: "Evening Run"
New Workout found: "Morning Swim"
New Workout found: "Afternoon Ride"
...
```

**Comment by ethanopp** [comment]
Yeah... I think I need to just update to flask-sqlalchemy... Will try and get a push out tomorrow

**Comment by ethanopp** [comment]
Alright so after doing a little research it definitely looks like its a threading issue with the sqlite operations... I've spent the last 4 hours or so trying to get flask-sqlalchemy to work... and for the life of me can't figure it out...

Seems pretty straight forward but none of the layouts load once I switch over to the SQLAlchemy()

...maybe another pair of eyes would help:
https://hackersandslackers.com/flask-sqlalchemy-database-models/

**Comment by ethanopp** [comment]
@pierretamisier this may have caused other issues... but I think its resolved the threading ones... will continue debugging later today
https://github.com/ethanopp/fitly/commit/6ca2f5463889c6ad09fda41c46d437863acfea9b

**Comment by pierretamisier** [comment]
I'll def have a look after I finish programming a csv upload to load all my past strava data thru http://flink.run !
